#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

set -a
source "$PROJECT_ROOT/.env"
set +a

export PROJECT_ROOT
export JAVA_HOME="$PROJECT_ROOT/$JAVA_RELATIVE_DIR"
export HADOOP_HOME="$PROJECT_ROOT/$HADOOP_RELATIVE_DIR"
export HADOOP_CONF_DIR="$PROJECT_ROOT/$HADOOP_CONF_RELATIVE_DIR"

export HDFS_STORE_DIR="$PROJECT_ROOT/$HDFS_STORE_RELATIVE_DIR"
export HDFS_TMP_DIR="$PROJECT_ROOT/$HDFS_TMP_RELATIVE_DIR"
export HDFS_NAMENODE_DIR="$PROJECT_ROOT/$HDFS_NAMENODE_RELATIVE_DIR"
export HDFS_DATANODE_DIR="$PROJECT_ROOT/$HDFS_DATANODE_RELATIVE_DIR"

export PATH="$JAVA_HOME/bin:$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin"

echo "[project-env] PROJECT_ROOT=$PROJECT_ROOT"
echo "[project-env] JAVA_HOME=$JAVA_HOME"
echo "[project-env] HADOOP_HOME=$HADOOP_HOME"
echo "[project-env] HADOOP_CONF_DIR=$HADOOP_CONF_DIR"
