#!/bin/bash
set -e

PROJECT_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
SCREENSHOT_DIR="$PROJECT_ROOT/artifacts/screenshots"
mkdir -p "$SCREENSHOT_DIR"

echo "============================================================"
echo "    Script hỗ trợ chụp màn hình cho báo cáo"
echo "    Thư mục screenshots: $SCREENSHOT_DIR"
echo "============================================================"
echo ""
echo "Hướng dẫn:"
echo "1. Chạy từng lệnh bên dưới và chụp màn hình terminal"
echo "2. Đặt tên file theo hướng dẫn"
echo "3. Lưu vào thư mục $SCREENSHOT_DIR"
echo ""
echo "============================================================"
echo "    NHÓM 1: Architecture & HDFS"
echo "============================================================"
echo ""
echo "2. java_hadoop_version.png:"
echo "   Chạy: java -version"
echo "   Chạy: hadoop version"
echo ""
echo "3. jps_after_start.png:"
echo "   Chạy: source $PROJECT_ROOT/scripts/activate.sh"
echo "   Chạy: hdfs --daemon start namenode"
echo "   Chạy: hdfs --daemon start datanode"
echo "   Chạy: jps"
echo ""
echo "4. hdfs_webui.png:"
echo "   Mở trình duyệt: http://localhost:9870"
echo "   Chụp màn hình phần Summary"
echo ""
echo "5. hdfs_ls_du.png:"
echo "   Chạy: source $PROJECT_ROOT/scripts/activate.sh"
echo "   Chạy: hdfs dfs -ls /project/cinema/raw/movielens"
echo "   Chạy: hdfs dfs -du -h /project/cinema/raw/movielens"
echo ""
echo "============================================================"
echo "    NHÓM 2: Data Input"
echo "============================================================"
echo ""
echo "6. tmdb_preview.png:"
echo "   Mở file data/raw/tmdb_revenue.csv trong Excel/VS Code"
echo "   Chụp 5-10 dòng đầu tiên"
echo ""
echo "============================================================"
echo "    NHÓM 3: Preprocessing"
echo "============================================================"
echo ""
echo "10. preprocessing_output.png:"
echo "   Chạy: chmod +x $PROJECT_ROOT/scripts/run_preprocessing.sh"
echo "   Chạy: $PROJECT_ROOT/scripts/run_preprocessing.sh"
echo "   Chụp dòng cuối: 'Data Preprocessing Pipeline Completed!'"
echo ""
echo "11. mongodb_count.png:"
echo "   Chạy: mongosh 'mongodb://localhost:27017'"
echo "   Chạy: use cinema_dw"
echo "   Chạy: db.movies.countDocuments()"
echo "   Chạy: db.ratings.countDocuments()"
echo "   Chạy: db.tags.countDocuments()"
echo ""
echo "12. mongodb_compass_overview.png:"
echo "   Mở MongoDB Compass"
echo "   Kết nối: mongodb://localhost:27017"
echo "   Chụp tab Databases với cinema_dw"
echo ""
echo "============================================================"
echo "    NHÓM 4: Analytic & Dashboard"
echo "============================================================"
echo ""
echo "14. streamlit_dashboard_full.png:"
echo "   Chạy: source $PROJECT_ROOT/scripts/activate.sh"
echo "   Chạy: streamlit run $PROJECT_ROOT/visual/streamlit_app/app.py"
echo "   Mở trình duyệt: http://localhost:8501"
echo "   Chụp toàn màn hình dashboard"
echo ""
echo "============================================================"
echo "    LƯU Ý QUAN TRỌNG"
echo "============================================================"
echo "- Các file Mermaid diagram nằm ở: $PROJECT_ROOT/artifacts/diagrams/"
echo "- Dùng https://mermaid.live/ để export sang PNG"
echo "- Đảm bảo MongoDB và HDFS đang chạy trước khi chụp"
echo "- File tmdb_revenue.csv cần được tải và đặt vào data/raw/"
echo "============================================================"
